
export const POINTS_FOR_CREATING_QUESTION = 10;
export const POINTS_FOR_CREATING_ANSWER = 5;

export const POINTS_FOR_RECEIVING_UPVOTE_ON_QUESTION = 10;
export const POINTS_FOR_RECEIVING_UPVOTE_ON_ANSWER = 5;

export const POINTS_FOR_RECEIVING_DOWNVOTE_ON_QUESTION = -5;
export const POINTS_FOR_RECEIVING_DOWNVOTE_ON_ANSWER = -5;

export const POINTS_FOR_UPVOTING_QUESTION = 2;
export const POINTS_FOR_UPVOTING_ANSWER = 1;

export const POINTS_FOR_DOWNVOTING_QUESTION = 2;
export const POINTS_FOR_DOWNVOTING_ANSWER = 1;